# import libraries and data set

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r'/Users/alisoncoolidge/Desktop/Happiness Project'

In [3]:
df = pd.read_csv(os.path.join(path, 'Datasets', 'UN Happiness Data.csv'))

In [4]:
# checking import
df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
0,Afghanistan,2008,3.723590,7.302574,0.450662,50.500000,0.718114,0.173169,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,2009,4.401778,7.472446,0.552308,50.799999,0.678896,0.195469,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,2010,4.758381,7.579183,0.539075,51.099998,0.600127,0.125859,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,2011,3.831719,7.552006,0.521104,51.400002,0.495901,0.167723,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,2012,3.782938,7.637953,0.520637,51.700001,0.530935,0.241247,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,8.241609,0.754147,52.150002,0.752826,-0.113937,0.751208,0.733641,0.224051,0.682647
2085,Zimbabwe,2018,3.616480,8.274620,0.775388,52.625000,0.762675,-0.084747,0.844209,0.657524,0.211726,0.550508
2086,Zimbabwe,2019,2.693523,8.196998,0.759162,53.099998,0.631908,-0.081540,0.830652,0.658434,0.235354,0.456455
2087,Zimbabwe,2020,3.159802,8.117733,0.717243,53.575001,0.643303,-0.029376,0.788523,0.660658,0.345736,0.577302
2088,Zimbabwe,2021,3.154578,8.153248,0.685151,54.049999,0.667636,-0.109439,0.756945,0.609917,0.241682,0.665703

In [5]:
df.describe()

,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
count,2089.000000,2089.000000,2062.000000,2076.000000,2031.000000,2057.000000,2009.000000,1976.000000,2065.000000,2073.000000,1873.000000
mean,2013.727621,5.473747,9.378408,0.811542,63.180326,0.745462,0.000102,0.746474,0.651421,0.270544,0.483914
std,4.455614,1.115567,1.143520,0.118935,6.948546,0.140751,0.161082,0.186136,0.105954,0.085849,0.191515
min,2005.000000,2.178809,5.526723,0.290184,6.720000,0.257534,-0.335739,0.035198,0.178886,0.082737,0.068769
25%,2010.000000,4.651972,8.473547,0.747664,58.965000,0.651689,-0.113172,0.689840,0.570057,0.207652,0.334808
50%,2014.000000,5.405246,9.463269,0.834770,64.980003,0.767357,-0.023366,0.801339,0.662837,0.260328,0.467046
75%,2017.000000,6.294282,10.347656,0.904682,68.362499,0.857677,0.090584,0.870789,0.737176,0.321706,0.616302
max,2021.000000,8.018934,11.665803,0.987343,74.349998,0.985178,0.706377,0.983276,0.883586,0.704590,0.993604

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country name                       2089 non-null   object
 1   year                               2089 non-null   int64
 2   Life Ladder                        2089 non-null   float64
 3   Log GDP per capita                 2062 non-null   float64
 4   Social support                     2076 non-null   float64
 5   Healthy life expectancy at birth   2031 non-null   float64
 6   Freedom to make life choices       2057 non-null   float64
 7   Generosity                         2009 non-null   float64
 8   Perceptions of corruption          1976 non-null   float64
 9   Positive affect                    2065 non-null   float64
 10  Negative affect                    2073 non-null   float64
 11  Confidence in national government  1873 non-null   float64
dtypes: float64(10), int64(1), object(1)
memory usage: 196.0+ KB

In [7]:
df.shape

(2089, 12)

# CLEANING, WRANGLING, CONSISTENCY

Change column names for clarity 
Check/ change data types 
Check for mixed data 
Drop unnecessary columns 
Check for missing values
Check for duplicates

In [8]:
# Change column names for clarity -- Log GDP per capita to just GDP per capita

df.rename(columns = {'Log GDP per capita' : 'GDP per capita'}, inplace = True)

In [9]:
# Check for rename

df.head(1)

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
0,Afghanistan,2008,3.72359,7.302574,0.450662,50.5,0.718114,0.173169,0.881686,0.414297,0.258195,0.612072

In [10]:
# Check data types -- change year to object

df['year'] = df['year'].astype('object')

In [11]:
# checking data type change

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country name                       2089 non-null   object
 1   year                               2089 non-null   object
 2   Life Ladder                        2089 non-null   float64
 3   GDP per capita                     2062 non-null   float64
 4   Social support                     2076 non-null   float64
 5   Healthy life expectancy at birth   2031 non-null   float64
 6   Freedom to make life choices       2057 non-null   float64
 7   Generosity                         2009 non-null   float64
 8   Perceptions of corruption          1976 non-null   float64
 9   Positive affect                    2065 non-null   float64
 10  Negative affect                    2073 non-null   float64
 11  Confidence in national government  1873 non-null   float64
dtypes: float64(10), object(2)
memory usage: 196.0+ KB

In [12]:
# Check for mixed type data

for col in df.columns.tolist():
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df[weird]) > 0:
    print (col)

In [ ]:
# no mixed type data to address
# no columns need to be dropped, all relevant to analysis

In [17]:
# creating a subset of the  dataframe to view all the missing values:

df_nan = df[df['GDP per capita'].isnull() == True]

In [18]:
df_nan

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
12,Afghanistan,2021,2.436034,NaN,0.454175,54.549999,0.394306,NaN,0.946299,0.178886,0.606713,0.255620
449,Cuba,2006,5.417869,NaN,0.969595,68.000000,0.281458,NaN,NaN,0.596187,0.276602,0.513176
463,Cyprus,2021,6.269202,NaN,0.855357,72.800003,0.717639,NaN,0.876456,0.641121,0.274684,0.321940
758,Hong Kong S.A.R. of China,2021,5.321551,NaN,0.821089,NaN,0.668631,NaN,0.389589,0.534148,0.223565,0.495274
971,Kosovo,2007,5.103906,NaN,0.847812,NaN,0.381364,NaN,0.894462,0.613723,0.236699,0.375601
985,Kosovo,2021,6.648499,NaN,0.848839,NaN,0.840117,NaN,0.842379,0.578284,0.116078,0.577199
1165,Malta,2021,6.443715,NaN,0.897113,71.599998,0.889074,NaN,0.752516,0.635254,0.375325,0.662025
1373,North Cyprus,2012,5.463305,NaN,0.871150,NaN,0.692568,NaN,0.854730,0.548641,0.405435,0.414000
1374,North Cyprus,2013,5.566803,NaN,0.869274,NaN,0.775383,NaN,0.715356,0.506441,0.442972,0.401788
1375,North Cyprus,2014,5.785979,NaN,0.801802,NaN,0.829677,NaN,0.692221,0.570316,0.311336,0.412390
1376,North Cyprus,2015,5.842550,NaN,0.791383,NaN,0.785353,NaN,0.659180,0.566849,0.318930,0.439621
1377,North Cyprus,2016,5.827128,NaN,0.807690,NaN,0.796234,NaN,0.670191,0.531509,0.346465,0.440595
1378,North Cyprus,2018,5.608056,NaN,0.837392,NaN,0.797066,NaN,0.613837,0.398250,0.261868,0.378324
1379,North Cyprus,2019,5.466615,NaN,0.803295,NaN,0.792735,NaN,0.640059,0.404271,0.296411,0.370310
1647,Singapore,2021,6.586717,NaN,0.876409,73.800003,0.878701,NaN,0.144935,0.696990,0.159802,0.897622
1678,Somaliland region,2009,4.991400,NaN,0.879567,NaN,0.746304,NaN,0.513372,0.707874,0.112012,0.538495
1679,Somaliland region,2010,4.657363,NaN,0.829005,NaN,0.820182,NaN,0.471094,0.631947,0.083426,0.587192
1680,Somaliland region,2011,4.930572,NaN,0.787962,NaN,0.858104,NaN,0.357341,0.690514,0.122244,0.760764
1681,Somaliland region,2012,5.057314,NaN,0.786291,NaN,0.758219,NaN,0.333832,0.686732,0.152428,0.651242
1714,South Sudan,2014,3.831992,NaN,0.545118,52.880001,0.567259,NaN,0.741541,0.578410,0.428320,0.446467
1715,South Sudan,2015,4.070771,NaN,0.584781,53.000000,0.511631,NaN,0.709606,0.552726,0.449795,0.509234
1716,South Sudan,2016,2.888112,NaN,0.532152,53.174999,0.439919,NaN,0.785318,0.593741,0.549257,0.456288
1717,South Sudan,2017,2.816622,NaN,0.556823,53.349998,0.456011,NaN,0.761270,0.564999,0.517364,0.461551
1801,Taiwan Province of China,2020,6.751068,NaN,0.900833,NaN,0.798835,NaN,0.710567,0.743169,0.082737,0.579727
1802,Taiwan Province of China,2021,6.246744,NaN,0.866298,NaN,0.818467,NaN,0.675439,0.667417,0.122980,0.437148
2028,Venezuela,2020,4.573830,NaN,0.805224,64.224998,0.611815,NaN,0.811319,0.689349,0.396250,0.251202
2029,Venezuela,2021,5.107553,NaN,0.812418,64.050003,0.595620,NaN,0.823898,0.697587,0.389351,0.175912

In [19]:
df_nan2 = df[df['Social support'].isnull() == True]

In [20]:
df_nan2

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
27,Algeria,2010,5.463567,9.302982,NaN,65.500000,0.592696,-0.207632,0.618038,NaN,NaN,NaN
120,Bahrain,2014,6.165134,10.783138,NaN,65.959999,NaN,NaN,NaN,NaN,NaN,NaN
311,Canada,2007,7.481753,10.733970,NaN,70.620003,0.930341,0.247342,0.405608,0.811577,0.256810,0.637824
495,Djibouti,2010,5.005811,7.934187,NaN,54.599998,0.763730,-0.066950,0.596910,NaN,NaN,0.692278
992,Kuwait,2014,6.180139,10.944602,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
1246,Morocco,2010,4.383247,8.745358,NaN,62.500000,0.662900,-0.162961,0.900453,NaN,NaN,NaN
1405,Oman,2011,6.852982,10.392095,NaN,62.340000,0.916293,0.022032,NaN,NaN,0.295164,NaN
1528,Qatar,2010,6.849653,11.471148,NaN,64.699997,NaN,0.103960,NaN,NaN,NaN,NaN
1531,Qatar,2015,6.374529,11.471742,NaN,66.400002,NaN,NaN,NaN,NaN,NaN,NaN
1866,Tunisia,2009,5.025470,9.262184,NaN,66.220001,0.781496,-0.124318,0.722211,NaN,NaN,NaN
1943,United Arab Emirates,2014,6.539855,11.042156,NaN,65.339996,NaN,NaN,NaN,NaN,NaN,NaN
1968,United States,2007,7.512688,10.930840,NaN,66.760002,0.871904,0.194548,0.633035,0.755915,0.231679,0.393245
2041,Vietnam,2017,5.175279,8.875628,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df_nan3 = df[df['Healthy life expectancy at birth'].isnull() == True]

In [22]:
df_nan3

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
747,Hong Kong S.A.R. of China,2006,5.511187,10.746424,0.812178,NaN,0.909820,0.153046,0.355985,0.591140,0.235955,0.663938
748,Hong Kong S.A.R. of China,2008,5.137262,10.815546,0.840222,NaN,0.922211,0.293682,0.273945,0.575073,0.236634,0.677437
749,Hong Kong S.A.R. of China,2009,5.397056,10.788493,0.834716,NaN,0.918026,0.305077,0.272125,0.606459,0.210104,0.619142
750,Hong Kong S.A.R. of China,2010,5.642835,10.846634,0.857314,NaN,0.890418,0.329340,0.255775,0.600561,0.183106,0.634737
751,Hong Kong S.A.R. of China,2011,5.474011,10.886932,0.846060,NaN,0.894330,0.231902,0.244887,0.582491,0.195712,0.584562
752,Hong Kong S.A.R. of China,2012,5.483765,10.892753,0.826426,NaN,0.879752,0.219744,0.379783,0.580223,0.183349,0.497906
753,Hong Kong S.A.R. of China,2014,5.458051,10.939503,0.833558,NaN,0.843082,0.221097,0.422960,0.602495,0.242868,0.457823
754,Hong Kong S.A.R. of China,2016,5.498421,10.969857,0.832078,NaN,0.799743,0.097504,0.402813,0.568555,0.213115,0.449610
755,Hong Kong S.A.R. of China,2017,5.362475,10.999584,0.831066,NaN,0.830657,0.137305,0.415810,0.535812,0.200593,0.545041
756,Hong Kong S.A.R. of China,2019,5.659317,10.995179,0.855826,NaN,0.726852,0.064956,0.431974,0.519312,0.357607,0.332540
757,Hong Kong S.A.R. of China,2020,5.295341,10.935853,0.812943,NaN,0.705452,-0.072825,0.380351,0.521671,0.210314,0.442211
758,Hong Kong S.A.R. of China,2021,5.321551,NaN,0.821089,NaN,0.668631,NaN,0.389589,0.534148,0.223565,0.495274
971,Kosovo,2007,5.103906,NaN,0.847812,NaN,0.381364,NaN,0.894462,0.613723,0.236699,0.375601
972,Kosovo,2008,5.521660,8.858291,0.883843,NaN,NaN,0.098464,0.849059,0.499646,0.317828,0.549438
973,Kosovo,2009,5.891433,8.899382,0.830427,NaN,0.506415,0.207480,0.967839,0.527557,0.168830,NaN
974,Kosovo,2010,5.176601,8.939567,0.707959,NaN,0.451444,0.175517,0.967272,0.672983,0.117717,NaN
975,Kosovo,2011,4.859502,8.992258,0.759102,NaN,0.588979,0.008153,0.919212,0.603740,0.124438,NaN
976,Kosovo,2012,5.639588,9.000282,0.757147,NaN,0.635793,0.032394,0.949651,0.561854,0.099630,0.312399
977,Kosovo,2013,6.125758,9.046240,0.720750,NaN,0.568463,0.118774,0.935095,0.649957,0.202731,0.361421
978,Kosovo,2014,5.000375,9.082124,0.705632,NaN,0.441391,0.014447,0.775201,0.551719,0.205950,0.344450
979,Kosovo,2015,5.077461,9.153252,0.805271,NaN,0.561048,0.181899,0.850647,0.684578,0.179989,0.328998
980,Kosovo,2016,5.759412,9.213440,0.823803,NaN,0.827399,0.124838,0.940898,0.588413,0.149607,0.313765
981,Kosovo,2017,6.149200,9.253033,0.792087,NaN,0.857677,0.116697,0.925192,0.616912,0.185879,0.298196
982,Kosovo,2018,6.391826,9.283142,0.822407,NaN,0.889737,0.268571,0.922078,0.642224,0.170248,0.347547
983,Kosovo,2019,6.425144,9.334190,0.842511,NaN,0.841190,0.246104,0.920297,0.611600,0.140792,0.308195
984,Kosovo,2020,6.294414,9.286884,0.792374,NaN,0.879838,0.305646,0.909894,0.592678,0.201458,0.247848
985,Kosovo,2021,6.648499,NaN,0.848839,NaN,0.840117,NaN,0.842379,0.578284,0.116078,0.577199
1373,North Cyprus,2012,5.463305,NaN,0.871150,NaN,0.692568,NaN,0.854730,0.548641,0.405435,0.414000
1374,North Cyprus,2013,5.566803,NaN,0.869274,NaN,0.775383,NaN,0.715356,0.506441,0.442972,0.401788
1375,North Cyprus,2014,5.785979,NaN,0.801802,NaN,0.829677,NaN,0.692221,0.570316,0.311336,0.412390
1376,North Cyprus,2015,5.842550,NaN,0.791383,NaN,0.785353,NaN,0.659180,0.566849,0.318930,0.439621
1377,North Cyprus,2016,5.827128,NaN,0.807690,NaN,0.796234,NaN,0.670191,0.531509,0.346465,0.440595
1378,North Cyprus,2018,5.608056,NaN,0.837392,NaN,0.797066,NaN,0.613837,0.398250,0.261868,0.378324
1379,North Cyprus,2019,5.466615,NaN,0.803295,NaN,0.792735,NaN,0.640059,0.404271,0.296411,0.370310
1427,Palestinian Territories,2011,4.751220,8.451591,0.750832,NaN,0.521889,-0.125791,0.750208,0.499074,0.387651,0.487110
1428,Palestinian Territories,2012,4.646608,8.598372,0.782169,NaN,0.541583,-0.158610,0.730194,0.559733,0.378504,0.466043
1429,Palestinian Territories,2013,4.844028,8.594526,0.760900,NaN,0.453903,-0.158182,0.779646,0.536739,0.365276,0.438161
1430,Palestinian Territories,2014,4.721938,8.618412,0.775087,NaN,0.657050,-0.158626,0.804165,0.504632,0.380452,0.474314
1431,Palestinian Territories,2015,4.695239,8.683147,0.766101,NaN,0.556041,-0.167896,0.774301,0.536447,0.369085,0.445856
1432,Palestinian Territories,2016,4.906618,8.737954,0.817771,NaN,0.607669,-0.146673,0.812465,0.543776,0.377642,0.463772
1433,Palestinian Territories,2017,4.628133,8.733621,0.824345,NaN,0.631611,-0.180933,0.830646,0.533918,0.416072,0.414401
1434,Palestinian Territories,2018,4.553922,8.717741,0.819479,NaN,0.654535,-0.157972,0.813780,0.528392,0.418929,0.392373
1435,Palestinian Territories,2019,4.482537,8.716377,0.832550,NaN,0.653488,-0.130439,0.829283,0.538073,0.399672,0.402750
1678,Somaliland region,2009,4.991400,NaN,0.879567,NaN,0.746304,NaN,0.513372,0.707874,0.112012,0.538495
1679,Somaliland region,2010,4.657363,NaN,0.829005,NaN,0.820182,NaN,0.471094,0.631947,0.083426,0.587192
1680,Somaliland region,2011,4.930572,NaN,0.787962,NaN,0.858104,NaN,0.357341,0.690514,0.122244,0.760764
1681,Somaliland region,2012,5.057314,NaN,0.786291,NaN,0.758219,NaN,0.333832,0.686732,0.152428,0.651242
1792,Taiwan Province of China,2011,6.308915,10.693417,0.862521,NaN,0.761488,0.033636,0.754584,0.727106,0.112288,0.472067
1793,Taiwan Province of China,2012,6.125917,10.717881,0.825072,NaN,0.698195,0.019110,0.802829,0.701637,0.140011,0.335142
1794,Taiwan Province of China,2013,6.340344,10.723532,0.816993,NaN,0.690071,0.000912,0.841232,0.754478,0.124445,0.264499
1795,Taiwan Province of China,2014,6.363497,10.749411,0.870012,NaN,0.692900,0.092918,0.865741,0.767370,0.108366,0.270723
1796,Taiwan Province of China,2015,6.450088,10.778760,0.885389,NaN,0.700810,0.020643,0.857195,0.750358,0.129349,0.270260
1797,Taiwan Province of China,2016,6.512851,10.768047,0.894989,NaN,0.718925,-0.045145,0.810521,0.742680,0.108305,0.404713
1798,Taiwan Province of China,2017,6.359451,10.774066,0.891119,NaN,0.759655,-0.066123,0.742780,0.715303,0.114123,0.322822
1799,Taiwan Province of China,2018,6.467005,10.780802,0.896459,NaN,0.741033,-0.175206,0.735971,0.745919,0.092696,0.311723
1800,Taiwan Province of China,2019,6.537090,10.797460,0.893431,NaN,0.814484,-0.127218,0.718112,0.762097,0.093412,0.431495
1801,Taiwan Province of China,2020,6.751068,NaN,0.900833,NaN,0.798835,NaN,0.710567,0.743169,0.082737,0.579727
1802,Taiwan Province of China,2021,6.246744,NaN,0.866298,NaN,0.818467,NaN,0.675439,0.667417,0.122980,0.437148

In [23]:
df_nan4 = df[df['Freedom to make life choices'].isnull() == True]

In [24]:
df_nan4

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
30,Algeria,2014,6.354898,9.351205,0.818189,65.900002,NaN,NaN,NaN,0.558359,0.176866,NaN
31,Algeria,2016,5.340854,9.378069,0.748588,66.099998,NaN,NaN,NaN,0.565026,0.377112,NaN
120,Bahrain,2014,6.165134,10.783138,NaN,65.959999,NaN,NaN,NaN,NaN,NaN,NaN
278,Cambodia,2006,3.568745,7.746449,0.793081,57.639999,NaN,0.255501,0.829181,NaN,0.341023,0.736355
361,China,2006,4.560495,8.696139,0.747011,65.660004,NaN,NaN,NaN,0.657659,0.169580,NaN
362,China,2007,4.862862,8.823968,0.810852,65.919998,NaN,-0.176961,NaN,0.663977,0.158614,NaN
369,China,2014,5.195619,9.380201,0.820366,67.739998,NaN,-0.217615,NaN,0.709763,0.111518,NaN
370,China,2015,5.303878,9.442431,0.793734,68.000000,NaN,-0.245284,NaN,0.666827,0.171315,NaN
371,China,2016,5.324956,9.502946,0.741703,68.125000,NaN,-0.228405,NaN,0.683256,0.145625,NaN
531,Egypt,2008,4.631741,9.186407,0.738364,61.580002,NaN,-0.088120,0.913642,0.627448,0.301018,NaN
834,Iraq,2013,4.725017,9.227219,0.728285,60.840000,NaN,-0.047180,0.709726,NaN,0.554279,0.500670
923,Jordan,2005,6.294660,9.266464,0.920013,65.800003,NaN,NaN,0.669727,0.629833,0.239560,0.800150
925,Jordan,2008,4.930058,9.364168,0.766224,66.339996,NaN,-0.130019,0.709403,0.655700,0.331201,NaN
972,Kosovo,2008,5.521660,8.858291,0.883843,NaN,NaN,0.098464,0.849059,0.499646,0.317828,0.549438
992,Kuwait,2014,6.180139,10.944602,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
1017,Laos,2012,4.876085,8.610509,0.692628,58.160000,NaN,0.231592,NaN,0.740587,0.386679,NaN
1100,Madagascar,2006,3.979751,7.375728,0.711135,54.139999,NaN,-0.037979,NaN,0.562594,0.161333,0.713698
1528,Qatar,2010,6.849653,11.471148,NaN,64.699997,NaN,0.103960,NaN,NaN,NaN,NaN
1531,Qatar,2015,6.374529,11.471742,NaN,66.400002,NaN,NaN,NaN,NaN,NaN,NaN
1575,Saudi Arabia,2005,7.079644,10.698956,0.867819,61.200001,NaN,NaN,0.505149,0.680691,0.242553,NaN
1815,Tajikistan,2018,5.497469,8.136027,0.875243,61.849998,NaN,-0.068769,0.577946,0.631739,0.219794,NaN
1816,Tajikistan,2019,5.464015,8.183513,0.879823,62.000000,NaN,-0.048814,0.490029,0.663063,0.178497,NaN
1817,Tajikistan,2020,5.373399,8.204556,0.789745,62.150002,NaN,-0.049468,0.549786,0.651894,0.344161,NaN
1818,Tajikistan,2021,5.286824,8.250255,0.882889,62.299999,NaN,-0.064694,0.498925,0.655013,0.240200,NaN
1895,Turkmenistan,2009,6.567713,8.989171,0.923846,59.779999,NaN,-0.102557,NaN,0.695308,0.151584,NaN
1896,Turkmenistan,2011,5.791755,9.181698,0.964419,60.419998,NaN,0.017344,NaN,0.576616,0.122068,NaN
1943,United Arab Emirates,2014,6.539855,11.042156,NaN,65.339996,NaN,NaN,NaN,NaN,NaN,NaN
2001,Uzbekistan,2009,5.260721,8.462947,0.904678,62.060001,NaN,0.008256,0.610258,0.646040,0.158657,NaN
2002,Uzbekistan,2010,5.095342,8.507943,0.903226,62.299999,NaN,-0.035007,0.518720,0.664853,0.151883,NaN
2038,Vietnam,2014,5.084923,8.715804,0.792168,64.820000,NaN,-0.000577,NaN,0.633852,0.240607,NaN
2039,Vietnam,2015,5.076315,8.770014,0.848677,64.900002,NaN,0.084839,NaN,0.583119,0.232416,NaN
2041,Vietnam,2017,5.175279,8.875628,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_nan5 = df[df['Generosity'].isnull() == True]

In [26]:
df_nan5

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
12,Afghanistan,2021,2.436034,NaN,0.454175,54.549999,0.394306,NaN,0.946299,0.178886,0.606713,0.255620
30,Algeria,2014,6.354898,9.351205,0.818189,65.900002,NaN,NaN,NaN,0.558359,0.176866,NaN
31,Algeria,2016,5.340854,9.378069,0.748588,66.099998,NaN,NaN,NaN,0.565026,0.377112,NaN
72,Australia,2005,7.340688,10.650703,0.967892,69.800003,0.934973,NaN,0.390416,0.769770,0.238012,0.532063
118,Bahrain,2012,5.027187,10.715217,0.911350,65.480003,0.681823,NaN,0.437915,0.559416,0.380815,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1967,United States,2006,7.181794,10.921763,0.964572,66.779999,0.911496,NaN,0.600309,0.774833,0.260511,0.558029
2014,Venezuela,2005,7.169621,9.316229,0.955278,65.500000,0.838198,NaN,0.719800,0.802929,0.233014,0.491368
2028,Venezuela,2020,4.573830,NaN,0.805224,64.224998,0.611815,NaN,0.811319,0.689349,0.396250,0.251202
2029,Venezuela,2021,5.107553,NaN,0.812418,64.050003,0.595620,NaN,0.823898,0.697587,0.389351,0.175912
2041,Vietnam,2017,5.175279,8.875628,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df_nan6 = df[df['Perceptions of corruption'].isnull() == True]

In [29]:
df_nan6

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
30,Algeria,2014,6.354898,9.351205,0.818189,65.900002,NaN,NaN,NaN,0.558359,0.176866,NaN
31,Algeria,2016,5.340854,9.378069,0.748588,66.099998,NaN,NaN,NaN,0.565026,0.377112,NaN
120,Bahrain,2014,6.165134,10.783138,NaN,65.959999,NaN,NaN,NaN,NaN,NaN,NaN
121,Bahrain,2015,6.007375,10.781260,0.852551,66.199997,0.849521,0.109754,NaN,0.653345,0.302972,NaN
122,Bahrain,2016,6.169673,10.777658,0.862700,66.125000,0.888691,0.085865,NaN,0.736220,0.283466,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2039,Vietnam,2015,5.076315,8.770014,0.848677,64.900002,NaN,0.084839,NaN,0.583119,0.232416,NaN
2041,Vietnam,2017,5.175279,8.875628,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN
2046,Yemen,2007,4.477133,8.211859,0.824969,58.720001,0.672685,0.011023,NaN,0.523652,0.378784,0.465138
2054,Yemen,2016,3.825631,7.552322,0.775407,58.174999,0.532964,-0.138727,NaN,0.401007,0.227925,0.267581
2055,Yemen,2017,3.253560,7.243477,0.789555,57.950001,0.595191,-0.122040,NaN,0.368106,0.295064,0.247787

In [30]:
df_nan7 = df[df['Positive affect'].isnull() == True]

In [31]:
df_nan7

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
27,Algeria,2010,5.463567,9.302982,NaN,65.500000,0.592696,-0.207632,0.618038,NaN,NaN,NaN
120,Bahrain,2014,6.165134,10.783138,NaN,65.959999,NaN,NaN,NaN,NaN,NaN,NaN
134,Bangladesh,2014,4.635565,8.163840,0.577065,63.279999,0.735513,-0.098268,0.789375,NaN,0.230678,0.719101
143,Belarus,2008,5.463332,9.676768,0.903700,61.180000,0.639924,-0.221552,0.696496,NaN,0.245659,0.533609
278,Cambodia,2006,3.568745,7.746449,0.793081,57.639999,NaN,0.255501,0.829181,NaN,0.341023,0.736355
279,Cambodia,2007,4.155971,7.828795,0.675132,57.980000,0.818700,0.115733,0.878508,NaN,0.320335,0.638395
495,Djibouti,2010,5.005811,7.934187,NaN,54.599998,0.763730,-0.066950,0.596910,NaN,NaN,0.692278
834,Iraq,2013,4.725017,9.227219,0.728285,60.840000,NaN,-0.047180,0.709726,NaN,0.554279,0.500670
924,Jordan,2007,5.598057,9.341366,0.840607,66.160004,0.646079,-0.114654,0.663645,NaN,0.239750,0.771525
935,Jordan,2018,4.638934,9.211679,0.799544,67.599998,0.762420,-0.188076,NaN,NaN,NaN,NaN
936,Jordan,2019,4.452548,9.217453,0.792560,67.599998,0.725756,-0.167033,NaN,NaN,NaN,NaN
937,Jordan,2020,4.093992,9.191826,0.708840,67.599998,0.778533,-0.153874,NaN,NaN,NaN,NaN
992,Kuwait,2014,6.180139,10.944602,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
1137,Maldives,2018,5.197575,9.841285,0.913315,69.775002,0.854759,0.021234,NaN,NaN,NaN,NaN
1246,Morocco,2010,4.383247,8.745358,NaN,62.500000,0.662900,-0.162961,0.900453,NaN,NaN,NaN
1405,Oman,2011,6.852982,10.392095,NaN,62.340000,0.916293,0.022032,NaN,NaN,0.295164,NaN
1406,Pakistan,2005,5.224658,8.217931,0.590946,53.200001,0.629996,NaN,0.844436,NaN,0.237266,0.583483
1528,Qatar,2010,6.849653,11.471148,NaN,64.699997,NaN,0.103960,NaN,NaN,NaN,NaN
1531,Qatar,2015,6.374529,11.471742,NaN,66.400002,NaN,NaN,NaN,NaN,NaN,NaN
1866,Tunisia,2009,5.025470,9.262184,NaN,66.220001,0.781496,-0.124318,0.722211,NaN,NaN,NaN
1942,United Arab Emirates,2013,6.620951,11.000768,0.863716,65.279999,0.935979,NaN,NaN,NaN,0.291113,NaN
1943,United Arab Emirates,2014,6.539855,11.042156,NaN,65.339996,NaN,NaN,NaN,NaN,NaN,NaN
2031,Vietnam,2007,5.421688,8.394412,0.856023,64.260002,0.917836,0.088890,0.753934,NaN,0.205932,0.906148
2041,Vietnam,2017,5.175279,8.875628,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df_nan8 = df[df['Negative affect'].isnull() == True]

In [33]:
df_nan8

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
27,Algeria,2010,5.463567,9.302982,NaN,65.500000,0.592696,-0.207632,0.618038,NaN,NaN,NaN
120,Bahrain,2014,6.165134,10.783138,NaN,65.959999,NaN,NaN,NaN,NaN,NaN,NaN
495,Djibouti,2010,5.005811,7.934187,NaN,54.599998,0.763730,-0.066950,0.596910,NaN,NaN,0.692278
935,Jordan,2018,4.638934,9.211679,0.799544,67.599998,0.762420,-0.188076,NaN,NaN,NaN,NaN
936,Jordan,2019,4.452548,9.217453,0.792560,67.599998,0.725756,-0.167033,NaN,NaN,NaN,NaN
937,Jordan,2020,4.093992,9.191826,0.708840,67.599998,0.778533,-0.153874,NaN,NaN,NaN,NaN
992,Kuwait,2014,6.180139,10.944602,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
1137,Maldives,2018,5.197575,9.841285,0.913315,69.775002,0.854759,0.021234,NaN,NaN,NaN,NaN
1246,Morocco,2010,4.383247,8.745358,NaN,62.500000,0.662900,-0.162961,0.900453,NaN,NaN,NaN
1482,Philippines,2006,4.669946,8.561845,0.795313,61.360001,0.828273,0.062931,0.841299,0.755979,NaN,0.571571
1528,Qatar,2010,6.849653,11.471148,NaN,64.699997,NaN,0.103960,NaN,NaN,NaN,NaN
1531,Qatar,2015,6.374529,11.471742,NaN,66.400002,NaN,NaN,NaN,NaN,NaN,NaN
1866,Tunisia,2009,5.025470,9.262184,NaN,66.220001,0.781496,-0.124318,0.722211,NaN,NaN,NaN
1879,Turkey,2005,4.718734,9.812012,0.819936,66.099998,0.623115,NaN,0.876999,0.478680,NaN,0.595774
1943,United Arab Emirates,2014,6.539855,11.042156,NaN,65.339996,NaN,NaN,NaN,NaN,NaN,NaN
2041,Vietnam,2017,5.175279,8.875628,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_nan9 = df[df['Confidence in national government'].isnull() == True]

In [35]:
df_nan9

,Country name,year,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
14,Albania,2009,5.485470,9.241250,0.833047,67.320000,0.525223,-0.157363,0.863665,0.564474,0.279257,NaN
15,Albania,2010,5.268937,9.282614,0.733152,67.599998,0.568958,-0.171783,0.726262,0.576077,0.300060,NaN
16,Albania,2011,5.867422,9.310439,0.759434,67.879997,0.487496,-0.204296,0.877003,0.565759,0.256577,NaN
27,Algeria,2010,5.463567,9.302982,NaN,65.500000,0.592696,-0.207632,0.618038,NaN,NaN,NaN
28,Algeria,2011,5.317194,9.312737,0.810234,65.599998,0.529561,-0.182975,0.637982,0.502736,0.254897,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2042,Vietnam,2018,5.295547,8.934052,0.831945,65.199997,0.909260,-0.041581,0.808423,0.614404,0.191061,NaN
2043,Vietnam,2019,5.467451,8.992331,0.847592,65.300003,0.952469,-0.126406,0.787889,0.657786,0.185610,NaN
2044,Vietnam,2020,5.462342,9.011930,0.764510,65.400002,0.944707,0.085265,0.791134,0.699165,0.286374,NaN
2045,Vietnam,2021,5.540250,9.028702,0.799494,65.500000,0.896800,0.126362,0.797788,0.650598,0.280437,NaN
2057,Yemen,2019,4.196913,7.447973,0.870043,57.500000,0.651308,-0.100867,0.798228,0.481123,0.213043,NaN

In [ ]:
# note on NaNs: since they vary year to year and country to country, NaN's will be left as is, so as not to impact the statistical analysis.

In [36]:
# check for duplicates

df_dupes = df[df.duplicated()]

In [37]:
df_dupes

Empty DataFrame
Columns: [Country name, year, Life Ladder, GDP per capita, Social support, Healthy life expectancy at birth, Freedom to make life choices, Generosity, Perceptions of corruption, Positive affect, Negative affect, Confidence in national government]
Index: []

In [ ]:
# no duplicates to address

In [38]:
df.describe

<bound method NDFrame.describe of      Country name  year  Life Ladder  GDP per capita  Social support  \
0     Afghanistan  2008     3.723590        7.302574        0.450662
1     Afghanistan  2009     4.401778        7.472446        0.552308
2     Afghanistan  2010     4.758381        7.579183        0.539075
3     Afghanistan  2011     3.831719        7.552006        0.521104
4     Afghanistan  2012     3.782938        7.637953        0.520637
...           ...   ...          ...             ...             ...
2084     Zimbabwe  2017     3.638300        8.241609        0.754147
2085     Zimbabwe  2018     3.616480        8.274620        0.775388
2086     Zimbabwe  2019     2.693523        8.196998        0.759162
2087     Zimbabwe  2020     3.159802        8.117733        0.717243
2088     Zimbabwe  2021     3.154578        8.153248        0.685151

      Healthy life expectancy at birth  Freedom to make life choices  \
0                            50.500000                      0.718114
1                            50.799999                      0.678896
2                            51.099998                      0.600127
3                            51.400002                      0.495901
4                            51.700001                      0.530935
...                                ...                           ...
2084                         52.150002                      0.752826
2085                         52.625000                      0.762675
2086                         53.099998                      0.631908
2087                         53.575001                      0.643303
2088                         54.049999                      0.667636

      Generosity  Perceptions of corruption  Positive affect  Negative affect  \
0       0.173169                   0.881686         0.414297         0.258195
1       0.195469                   0.850035         0.481421         0.237092
2       0.125859                   0.706766         0.516907         0.275324
3       0.167723                   0.731109         0.479835         0.267175
4       0.241247                   0.775620         0.613513         0.267919
...          ...                        ...              ...              ...
2084   -0.113937                   0.751208         0.733641         0.224051
2085   -0.084747                   0.844209         0.657524         0.211726
2086   -0.081540                   0.830652         0.658434         0.235354
2087   -0.029376                   0.788523         0.660658         0.345736
2088   -0.109439                   0.756945         0.609917         0.241682

      Confidence in national government
0                              0.612072
1                              0.611545
2                              0.299357
3                              0.307386
4                              0.435440
...                                 ...
2084                           0.682647
2085                           0.550508
2086                           0.456455
2087                           0.577302
2088                           0.665703

[2089 rows x 12 columns]>

# statistical analysis

In [40]:
df.describe()

,Life Ladder,GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
count,2089.000000,2062.000000,2076.000000,2031.000000,2057.000000,2009.000000,1976.000000,2065.000000,2073.000000,1873.000000
mean,5.473747,9.378408,0.811542,63.180326,0.745462,0.000102,0.746474,0.651421,0.270544,0.483914
std,1.115567,1.143520,0.118935,6.948546,0.140751,0.161082,0.186136,0.105954,0.085849,0.191515
min,2.178809,5.526723,0.290184,6.720000,0.257534,-0.335739,0.035198,0.178886,0.082737,0.068769
25%,4.651972,8.473547,0.747664,58.965000,0.651689,-0.113172,0.689840,0.570057,0.207652,0.334808
50%,5.405246,9.463269,0.834770,64.980003,0.767357,-0.023366,0.801339,0.662837,0.260328,0.467046
75%,6.294282,10.347656,0.904682,68.362499,0.857677,0.090584,0.870789,0.737176,0.321706,0.616302
max,8.018934,11.665803,0.987343,74.349998,0.985178,0.706377,0.983276,0.883586,0.704590,0.993604

In [42]:
# export dataframe

df.to_csv(os.path.join(path,'Datasets', 'happiness_data_clean.csv'))